-- =============================================================
-- SEED DATA — Sprint 1
-- 
-- NOTE: This file inserts a placeholder hash.
-- The real admin password hash is generated at application startup
-- by DataInitializer.java using BCryptPasswordEncoder on YOUR machine.
-- 
-- Running this file is optional — DataInitializer handles admin creation.
-- If you want to pre-insert, run the application once first to get
-- the correct hash for your machine, then copy it here.
--
-- Default admin credentials (set by DataInitializer.java):
--   Email:    admin@elearning.ub.cm
--   Password: Admin1234!
-- =============================================================
